/**
 * GitHub Repository Creator
 * Creates a new repo and pushes an initial commit via GitHub REST API
 */

import { GeneratedFile } from '../agents/developerAgent'

export interface GithubRepo {
  id: number
  full_name: string
  html_url: string
  clone_url: string
  ssh_url: string
  default_branch: string
}

type ProgressFn = (msg: string) => void

function getToken(): string {
  const token = import.meta.env.VITE_GITHUB_TOKEN
  if (!token) throw new Error('VITE_GITHUB_TOKEN not set.')
  return token
}

async function ghFetch<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = getToken()
  const res = await fetch(`https://api.github.com${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
      'Content-Type': 'application/json',
      ...(options.headers ?? {}),
    },
  })
  const data = await res.json()
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${data.message ?? JSON.stringify(data)}`)
  return data as T
}

// ─── Repository ───────────────────────────────────────────────────────────────

export async function createGithubRepo(
  name: string,
  description: string,
  onProgress?: ProgressFn
): Promise<GithubRepo> {
  onProgress?.(`Creating GitHub repo: ${name}`)
  const repoName = name.toLowerCase().replace(/[^a-z0-9-]/g, '-')

  const repo = await ghFetch<GithubRepo>('/user/repos', {
    method: 'POST',
    body: JSON.stringify({
      name: repoName,
      description,
      private: true,
      auto_init: false,
      has_issues: true,
      has_projects: false,
      has_wiki: false,
    }),
  })

  onProgress?.(`✅ Repo created: ${repo.html_url}`)
  return repo
}

// ─── Initial Commit ───────────────────────────────────────────────────────────

/** Push all generated files as an initial commit to the repo */
export async function pushInitialCommit(
  repo: GithubRepo,
  files: GeneratedFile[],
  onProgress?: ProgressFn
): Promise<string> {
  onProgress?.(`Pushing ${files.length} files to ${repo.full_name}...`)

  const [owner, repoName] = repo.full_name.split('/')

  // 1. Create blobs for each file
  const blobs = await Promise.all(
    files.slice(0, 50).map(async (f) => { // GitHub API allows max 100 files per tree
      const blob = await ghFetch<{ sha: string }>(`/repos/${owner}/${repoName}/git/blobs`, {
        method: 'POST',
        body: JSON.stringify({ content: f.content, encoding: 'utf-8' }),
      })
      return { path: f.path, mode: '100644' as const, type: 'blob' as const, sha: blob.sha }
    })
  )

  // 2. Create a tree
  const tree = await ghFetch<{ sha: string }>(`/repos/${owner}/${repoName}/git/trees`, {
    method: 'POST',
    body: JSON.stringify({ tree: blobs }),
  })

  // 3. Create the commit
  const commit = await ghFetch<{ sha: string }>(`/repos/${owner}/${repoName}/git/commits`, {
    method: 'POST',
    body: JSON.stringify({
      message: '🚀 Initial commit — generated by Bridgebox Voice AI',
      tree: tree.sha,
      parents: [],
    }),
  })

  // 4. Update HEAD reference
  await ghFetch(`/repos/${owner}/${repoName}/git/refs`, {
    method: 'POST',
    body: JSON.stringify({ ref: 'refs/heads/main', sha: commit.sha }),
  })

  onProgress?.(`✅ Initial commit pushed — ${repo.html_url}`)
  return commit.sha
}

// ─── Main helper ──────────────────────────────────────────────────────────────

export async function createAndPushRepo(
  appName: string,
  description: string,
  files: GeneratedFile[],
  onProgress?: ProgressFn
): Promise<GithubRepo | null> {
  const hasToken = !!import.meta.env.VITE_GITHUB_TOKEN

  if (!hasToken) {
    onProgress?.('⚡ Demo mode: skipping GitHub repo creation (VITE_GITHUB_TOKEN not set)')
    return null
  }

  const repo = await createGithubRepo(appName, description, onProgress)
  await pushInitialCommit(repo, files, onProgress)
  return repo
}
